#!/usr/bin/env bash

set -euo pipefail

declare -r SCRIPT_DIR=$(cd $(dirname $0) && pwd)
declare -r MANAGER_DIR=$(dirname ${SCRIPT_DIR})

# NOTE: This only works on OS X for now, and assumes the default username/password
# set up by Homebrew's Postgres installation.

# See https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds
# for an explanation of the hostname choice.

docker run \
  -e LIQUIBASE_HOST=host.docker.internal \
  -e LIQUIBASE_DATABASE=postgres \
  -e LIQUIBASE_USERNAME=$(whoami) \
  -v ${MANAGER_DIR}/db/changelog.xml:/workspace/changelog.xml \
  -v ${MANAGER_DIR}/db/changesets:/workspace/changesets \
  kilna/liquibase-postgres \
  liquibase update
