package org.broadinstitute.transporter.transfer.api

import java.util.UUID

import io.circe.Encoder

/**
  * Response generated by the successful submission of a transfer request.
  *
  * @param id unique ID for the request which can be used for status queries
  */
case class RequestAck(id: UUID)

object RequestAck {
  implicit val encoder: Encoder[RequestAck] = io.circe.derivation.deriveEncoder
}
