package org.broadinstitute.transporter.transfer.api

import java.util.UUID

import io.circe.Encoder

/**
  * Response generated by the successful submission of a transfer request.
  *
  * @param id unique ID for the request which can be used for status queries
  * @param updatedCount the number of transfers updated under request ID as part
  *                     of performing the operation
  */
case class RequestAck(id: UUID, updatedCount: Int)

object RequestAck {
  implicit val encoder: Encoder[RequestAck] = io.circe.derivation.deriveEncoder
}
